test_case_path : test_cases/e2e_test_cases.xlsx
browser: chrome
is_remote: false
remote_url: http://localhost:4444/wd/hub
chrome_path: E:\Downloads\my files\chrome-win64\chrome.exe
chromedriver_path: E:\Downloads\my files\chromedriver-win64\chromedriver.exe
edge_path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
edgedriver_path: C:\WebDrivers\msedgedriver.exe
browser_options:
  no-sandbox: true
  disable-dev-shm-usage: true
  disable-gpu: true
  remote-debugging-port: 9222
#  headless: true
