# The active environment to be used for the tests.
# This should match one of the environment keys defined below in 'environments'.
active_environment: DEV
# Path to the excel file containing the test cases.
test_cases_path: 'test_cases/api_test_cases.xlsx'
clear_saved_fields_after_test: false
# List of Test Case IDs to run.
# Specify one or more Test Case IDs here.
# If this list is empty, all test cases will be run.
tc_id_list:


# List of tags to filter test cases.
# Only test cases which contain any of these tags will be run.
# If this list is empty, all test cases will be run.
tags:

database:
  DEV:
    type: postgresql  # or oracle
    user: vhuang1
    password: Apj.com1
    host: 10.191.111.77
    port: 5432
    database: postgres
  UAT:
    type: oracle
    user: uat_user
    password: uat_password
    host: uat_host
    port: 1521
    service_name: uat_service_name
    min_connections: 1
    max_connections: 10
